services:
  - type: static
    name: idk-null
    publishDir: . # Change this to your folder name if your HTML/JS files are in a subfolder like 'public' or 'dist'
    routes:
      - path: /active/uv/uv.sw.js
        headers:
          - key: Service-Worker-Allowed
            value: /active/go/
            
